name: CI & Building i3Chain

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '17', '21' ]
    name: Java ${{ matrix.Java }} version
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java, Build and Test the App
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java }}
      - run: ./gradlew clean build
      
